// Generated by Claude Sonnet 4.6, prompted with my style, partially edited.

// eslint.config.js
import js from "@eslint/js"
import tseslint from "typescript-eslint"
import stylistic from "@stylistic/eslint-plugin"

export default tseslint.defineConfig(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      "@stylistic": stylistic,
    },
    rules: {
      // No trailing semicolons
      "@stylistic/semi": ["error", "never"],

      // Open brace on the same line as the signature (1tbs)
      "@stylistic/brace-style": ["error", "1tbs", { allowSingleLine: true }],
      "@stylistic/function-paren-newline": ["error", "multiline-arguments"],

      // Extra space BEFORE the return type colon, normal space after
      // e.g. `function foo() : string {`
      "@stylistic/type-annotation-spacing": [
        "error",
        {
          before: false,
          after: true,
          overrides: {
            // return type colon: space before AND after
            returnType: { before: true, after: true },
            // arrow `=>` keeps the conventional spacing
            arrow: { before: true, after: true },
          },
        },
      ],
      '@typescript-eslint/prefer-nullish-coalescing': 'warn',
    },
  },
)


// TO ADD:
// Add if not exists:
// - trailing comma for multi line args / objects / lists
// - Extra empty line at the end of file
// - Warn on ==
